### ISSUE TITLE
html build script

### ISSUE THREAD

**Issue by bommezijn** [dewarian/progressive-web-apps-2021#3]
At the moment the script that build static HTML fails. This is because of an error at the includes in the template. Not sure where the problem lies.

```ZSH
(node:64411) UnhandledPromiseRejectionWarning: Error: ejs:1
 >> 1| <%- include('partials/head') %>
    2| <%- include('partials/header') %>
    3| <!-- <img src="static/test.png"> -->
    4| 

Could not find the include file "partials/head"
    at getIncludePath (/Users/nbmp/git/minor/progressive-web-apps-2021/node_modules/ejs/lib/ejs.js:183:13)
    at includeFile (/Users/nbmp/git/minor/progressive-web-apps-2021/node_modules/ejs/lib/ejs.js:309:19)
    at include (/Users/nbmp/git/minor/progressive-web-apps-2021/node_modules/ejs/lib/ejs.js:690:16)
    at eval (eval at compile (/Users/nbmp/git/minor/progressive-web-apps-2021/node_modules/ejs/lib/ejs.js:662:12), <anonymous>:10:17)
    at anonymous (/Users/nbmp/git/minor/progressive-web-apps-2021/node_modules/ejs/lib/ejs.js:692:17)
    at Object.exports.render (/Users/nbmp/git/minor/progressive-web-apps-2021/node_modules/ejs/lib/ejs.js:423:37)
    at renderTemplate (/Users/nbmp/git/minor/progressive-web-apps-2021/scripts/build-html.js:44:14)
    at /Users/nbmp/git/minor/progressive-web-apps-2021/scripts/build-html.js:29:18
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:64411) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:64411) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by bommezijn** [comment]
Fixed in commit 793f689.
